# Generated by Django 4.1.2 on 2024-07-04 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idCiudad', models.IntegerField(db_column='idCiudad', primary_key=True, serialize=False)),
                ('nombreCiudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CodePais',
            fields=[
                ('idCodPais', models.IntegerField(db_column='idCodPais', primary_key=True, serialize=False)),
                ('codigoPhonePais', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('rolEmpresa', models.CharField(db_column='idEmpresa', max_length=15, primary_key=True, serialize=False)),
                ('nombreEmpresa', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.IntegerField(db_column='idPais', primary_key=True, serialize=False)),
                ('nombrePais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('idRubro', models.IntegerField(db_column='idRubro', primary_key=True, serialize=False)),
                ('descRubro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('idSexo', models.IntegerField(db_column='idSexo', primary_key=True, serialize=False)),
                ('detalleSexo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('userMote', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
                ('userAp', models.CharField(max_length=50)),
                ('userMail', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('userNacimiento', models.DateField()),
                ('userWebPage', models.CharField(max_length=100)),
                ('userDireccion', models.CharField(max_length=100)),
                ('passwordUsuario', models.CharField(max_length=50)),
                ('idCiudad', models.ForeignKey(db_column='idCiudad', on_delete=django.db.models.deletion.CASCADE, to='bodega.ciudad')),
                ('idCodPais', models.ForeignKey(db_column='idCodPais', on_delete=django.db.models.deletion.CASCADE, to='bodega.codepais')),
                ('idSexo', models.ForeignKey(db_column='idSexo', on_delete=django.db.models.deletion.CASCADE, to='bodega.sexo')),
                ('rolEmpresa', models.ForeignKey(db_column='idEmpresa', on_delete=django.db.models.deletion.CASCADE, to='bodega.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.IntegerField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('descProducto', models.CharField(max_length=500)),
                ('peso', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('rolEmpresa', models.ForeignKey(db_column='idEmpresa', on_delete=django.db.models.deletion.CASCADE, to='bodega.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='idRubro',
            field=models.ForeignKey(db_column='idRubro', on_delete=django.db.models.deletion.CASCADE, to='bodega.rubro'),
        ),
        migrations.AddField(
            model_name='codepais',
            name='idPais',
            field=models.ForeignKey(db_column='idPais', on_delete=django.db.models.deletion.CASCADE, to='bodega.pais'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='idPais',
            field=models.ForeignKey(db_column='idPais', on_delete=django.db.models.deletion.CASCADE, to='bodega.pais'),
        ),
    ]
