# Generated by Django 4.1.2 on 2024-07-06 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_alter_ciudad_idciudad_alter_codepais_idcodpais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='idPais',
            field=models.ForeignKey(db_column='idPais', default=1, on_delete=django.db.models.deletion.CASCADE, to='bodega.pais'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.CharField(db_column='idUsuario', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='userNacimiento',
            field=models.CharField(max_length=100),
        ),
    ]
