# Generated by Django 4.1.2 on 2024-07-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_usuario_idpais_alter_usuario_idusuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
