# Generated by Django 4.1.2 on 2024-07-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_usuario_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='idCodPais',
        ),
        migrations.DeleteModel(
            name='CodePais',
        ),
    ]
