# Generated by Django 4.1.2 on 2024-07-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0006_alter_usuario_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='passwordUsuario',
            field=models.CharField(max_length=128),
        ),
    ]
